### ISSUE TITLE
Filter object in a raw fashion

### ISSUE THREAD

**Issue by matthieusabourin** [nuagenetworks/vsdcli#10]
Same comment for -f option. 
Sometimes i get stuck into using this option without defining the parameter.
And from time to time even with defining the parameter to filter on, this is not working.
For instance: vsd list vminterfaces -f "associatedFloatingIPAddress == '10.225.196.3'"
or vsd list vminterfaces -f "VMUUID == '953d4b87-f927-40eb-a795-9d4f04f82106'" are not able to retrieve existing object.

**Comment by primalmotion** [comment]
This is most likely a VSD server issue. You should open an issue against vsd. Once it got fixed it'll work using the cli or the sdk.

Thanks,
