### ISSUE TITLE
How do you request statistics data of an ACL rule?

### ISSUE THREAD

**Issue by pdellaert** [nuagenetworks/vsdcli#11]
When you use the API to request a statistics output, you do a GET on an e/ingressaclentrytemplate:

```
Remote Address:10.167.43.64:443
Request URL:https://10.167.43.64/nuage/api/v3_2/ingressaclentrytemplates/0252a4ab-e47b-4ce0-b2e0-62d200fa1254/statistics?numberOfDataPoints=120&startTime=1444050000&endTime=1444057200&metricTypes=INGRESS_BYTE_COUNT
Request Method:GET
```

This allows for the selection of the granularity and the time and type of metric. 

In a normal situation, a GET API call is matched with a list command in the CLI. But there is no way to allow for any extra parameters in the CLI to specify these fields. As such, it seems we can not request statistics with specific parameters.

Am i missing something?

**Comment by primalmotion** [comment]
I think you can't but it should be fairly easy to add.

When doing a `fetch()` or a `get()` etc, we'll add a `query_param` in which you will be able to pass a dict containing the params/value you need to pass

**Comment by primalmotion** [comment]
fixed in an upcoming release of something. will be announced later today
