### ISSUE TITLE
Feature request: json only output

### ISSUE THREAD

**Issue by pdellaert** [nuagenetworks/vsdcli#3]
Currently, if you use the ```--json``` , the output still contains a '[Success] ' line. This makes it harder to further parse the content with tools like jq. 

Would it be possible to either alter the ```--json``` option so it only outputs json and nothing else (on success)?

Or allow for another option which suppresses all output except for the json data itself.

Example: 
```
$ vsd list zonetemplate --in domaintemplate 427588ca-3bc0-42fb-bcfc-550066228278 -x ID name --json
[Success] 2 zonetemplates have been retrieved
[
    {
        "ID": "e326b109-0366-47b1-a32b-27bff13a7fa7",
        "name": "G1-AppZone"
    },
    {
        "ID": "773224ce-b12e-4a45-9907-a3e58594ca0c",
        "name": "G1-DBZone"
    }
]
```

**Comment by primalmotion** [comment]
Fixed by #4
