### ISSUE TITLE
Request objects in a raw fashion

### ISSUE THREAD

**Issue by matthieusabourin** [nuagenetworks/vsdcli#9]
Hi;
I'd like to retrieve objects without providing the hierarchy.
for instance, would it be possible to find a vport just by filtering on name/uuid, without having to retrieve parent object id? 
thks!!

**Comment by primalmotion** [comment]
Hi,

It won't be possible to find a vport using a filter across all existing ones. The API doesn't support it.
It is only possible to get them from its parent subnet or from its parent domain.

But it should be possible to get them according to their UUID (as the API would be /vports/<id>)

I'll check how we can add this

Thanks,

**Comment by matthieusabourin** [comment]
Cool!
Thanks for quick answer!

**Comment by primalmotion** [comment]
Actually it's already possible.

If you domain id is xxx

```
vsd show domains --id xxx
```
